#!/bin/bash

die() {
	echo "$1" >&2
	exit 1
}

SOURCE="$1"
DEST="$2"

[ -z "${DEST}" ] && die "usage"

cd "$(dirname $0)"

cp "${SOURCE}/"{mp3unicode.1,releases.xml} ./  || die "copy"

# 2. man2xhtml

man2html mp3unicode.1 | tail -n +3 | sed "s/&nbsp;//g" | xmllint --dropdtd --html --xmlout --output manpage.xhtml - || die "man2html"

# 3. generating xml pages
for xslpage in templates/pages/*.xsl; do
  htmlpage=`echo $xslpage | sed 's_templates/pages/\(.*\)xsl$_\1html_'`
  xsltproc --xinclude -o "${DEST}/$htmlpage" $xslpage project.xml || die "xsltproc"
done

for f in *.html; do
	cp "$f" "${DEST}"
done
cp sitemap.xml "${DEST}"

# 4. cleaning up
rm manpage.xhtml
rm mp3unicode.1 releases.xml

