#!/bin/bash

# 1. define variables

htdocs=`echo $1 | sed 's_/$__'`
ptrunk=`echo $2 | sed 's_/$__'`

if [ ! -z $htdocs ]; then

# 1.5. copy some files from the program trunk (since we don't want to use symbolic links)
if [ -z $ptrunk ]; then
ptrunk="../../mp3unicode/trunk"
fi

cp $ptrunk/{mp3unicode.1,releases.xml} ./

# 2. man2xhtml

man2html mp3unicode.1 | tail -n +3 | sed "s/&nbsp;//g" | xmllint --dropdtd --html --xmlout --output manpage.xhtml -

# 3. generating xml pages
for xslpage in templates/pages/*.xsl
do
  htmlpage=`echo $xslpage | sed 's_templates/pages/\(.*\)xsl$_\1html_'`
  xsltproc --xinclude -o $htdocs/$htmlpage $xslpage project.xml
done
echo "Html pages saved to $htdocs"

# 4. cleaning up
rm manpage.xhtml
rm mp3unicode.1 releases.xml

else
echo "Specify the path to htdocs."
fi
